### PR TITLE
Update license information

### PR DESCRIPTION
**Pull request by mikemckiernan**
Review HTML: https://nvidia.github.io/cloud-native-docs/review/pr-108/gpu-operator/latest/overview.html#licenses-and-contributing

I noticed that both the NGC pages for the driver container and the GDS container include "[License for Customer Use of NVIDIA Software](http://www.nvidia.com/content/DriverDownload-March2009/licence.php?lang=us)".  I left it in, but I'm willing to remove it if that's preferred.

### CODE REVIEW

**Comment by francisguillier** [comment]
@mikemckiernan 

Request from Anders was the following:

"Can you please change the license for all components listed on [https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/index.html](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.nvidia.com%2Fdatacenter%2Fcloud-native%2Fgpu-operator%2Flatest%2Findex.html&data=05%7C02%7Cfguillier%40nvidia.com%7C7e05baefb2444b9c537b08dcdd7b043e%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638628767634765488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=0zfYXoL3H8qqufcCZeGifVpduk0es6gbpoLztcZok%2BA%3D&reserved=0) currently under the Deep Learning Container license to the AI Product license? Here are the URLs:  [https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-software-license-agreement/](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nvidia.com%2Fen-us%2Fagreements%2Fenterprise-software%2Fnvidia-software-license-agreement%2F&data=05%7C02%7Cfguillier%40nvidia.com%7C7e05baefb2444b9c537b08dcdd7b043e%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638628767634774864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=gmKyAaqCbNkf%2F7NISVUUV6n1H4Y8fWalih4j50dEbfI%3D&reserved=0) and [https://www.nvidia.com/en-us/agreements/enterprise-software/product-specific-terms-for-ai-products/](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nvidia.com%2Fen-us%2Fagreements%2Fenterprise-software%2Fproduct-specific-terms-for-ai-products%2F&data=05%7C02%7Cfguillier%40nvidia.com%7C7e05baefb2444b9c537b08dcdd7b043e%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638628767634784006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=R4n7SdsP9L9iAJlA%2B80Qc7QBeBYRaikv0876yaeFu08%3D&reserved=0)."



So my understanding is we just need to update the current table and whenever it is mentioned "Deep Learning Container license", we replace it with "AI Product license"

Clicking on the  "AI Product license" should redirect to this link:
https://www.nvidia.com/en-us/agreements/enterprise-software/product-specific-terms-for-ai-products/

**Comment by francisguillier** [comment]
@mikemckiernan did you update the page?
Let me know if you need help

**Comment by mikemckiernan** [comment]
I updated the source, but didn't republish--thinking that we could catch a handful of updates before republishing.

If https://github.com/NVIDIA/cloud-native-docs/pull/111 looks good, then I'll merge and republish.  Thanks!

**Comment by francisguillier** [comment]
yes https://github.com/NVIDIA/cloud-native-docs/pull/111 LGTM

**Pull request merged**
